// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUvTCcFbK9rq5kRxiabFAzlZzpOe8mKv8',
    appId: '1:728059227919:web:fec2ae4e5434216071187a',
    messagingSenderId: '728059227919',
    projectId: 'money-manager-f1af0',
    authDomain: 'money-manager-f1af0.firebaseapp.com',
    storageBucket: 'money-manager-f1af0.appspot.com',
    measurementId: 'G-DSHBZ5VD6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3Hd0vlo6WBAxnpfhMM2aE7wNKwIOkbc',
    appId: '1:728059227919:android:80668425d6c4fdfa71187a',
    messagingSenderId: '728059227919',
    projectId: 'money-manager-f1af0',
    storageBucket: 'money-manager-f1af0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgtJYKcTBEXMZd-YdYtwpxAmnEnTGBZjM',
    appId: '1:728059227919:ios:81208080a364104b71187a',
    messagingSenderId: '728059227919',
    projectId: 'money-manager-f1af0',
    storageBucket: 'money-manager-f1af0.appspot.com',
    iosBundleId: 'br.com.baz.development.moneyManager',
  );
}
