name: Android Release

on:
  push:
    branches:
      - 'master'
      - 'release/**'
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"
        cache: gradle
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.7.3"
        channel: 'stable'
        cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: flutter packages get
    - name: Decode Keystore
      id: write_file
      uses: timheuer/base64-to-file@v1
      with:
        fileName: "keystore_filename.jks"
        encodedString: ${{ secrets.KEYSTORE }}
    - name: Build
      run: flutter build apk --release 
      env:
        ANDROID_KEYSTORE_PATH: ${{ steps.write_file.outputs.filePath }}
        ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
        ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

  deploy:
    name: Deploy APK Build on Firebase-Distribution
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: wzieba/Firebase-Distribution-Github-Action@v1.4.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          release_notes: "New release version"
          file: build/app/outputs/apk/release/app-release.apk
